### ISSUE TITLE
File .pot

### ISSUE THREAD

**Issue by marckaraujo** [jhorstmann/i18n#12]
How to generate the .pot file?

**Comment by lengsovandara** [comment]
How?

**Comment by atilacamurca** [comment]
To generate a `.pot` file you have to:

1. generate a `.po` file from your source code: `mvn i18n:init -Dlocale en_US`
1. the `.pot` file is created based on the `.po`file, using gettext's `msgfilter` command: `msgfilter -i en_US.po -o keys.pot --keep-header true`

The `msgfilter` command is part of the [gettext](https://www.gnu.org/software/gettext/) translation library.

Or you can use this online tool: <https://mlocati.github.io/jsgettext/>

**Comment by lengsovandara** [comment]
Thank you **atilacamurca** for explain. But I got error  
`msginit: error while opening "\src\main\po\key s.pot" for reading: No such file or directory`
It seem it required the `keys.pot` in order to generate the `.po` file.
![i18n-init](https://user-images.githubusercontent.com/2851961/47984561-8c52ec00-e109-11e8-8339-eba619bf4ec4.PNG)

**Comment by atilacamurca** [comment]
To generate the initial `.pot` file, try this command:

```
xgettext -ktrc:1c,2 -ktrnc:1c,2,3 -ktr -kmarktr -ktrn:1,2 -o src/main/po/keys.pot src/*.java
```

**Comment by jhorstmann** [comment]
I'm sorry, it's been about 3 years since I last worked on this project. Reading the code now, the `keys.pot` file should be generated by just executing `mvn i18n:gettext`. Afterwards you can use `mvn i18n:init -Dlocale=en_US` to create a new `.po` file based on the `.pot` template. Let me know if this works.

**Comment by lengsovandara** [comment]
It is working thank you!
